### ISSUE TITLE
racey redundant prompt in ReadPassword methods

### ISSUE THREAD

**Issue by slingamn** [ergochat/readline#6]
I bisected this to 62ab2cfd17947c6843ad015eb81c0c675ec22630. There is now a race where the password prompt can be printed an extra time. It's reproducible with `example/readline-pass-strength/readline-pass-strength.go`:

```
$ ./readline-pass-strength
✔ ENT New Password: 
✗ ENT New Password: Your password was: sdjflaksdf
```

I'm considering a more extensive refactor of how config updates are done, but I want to get a firm diagnosis for this first to make sure I'm solving the root cause.

**Comment by slingamn** [comment]
I decided not to worry about this for now because the example calls Refresh from inside a listener:

https://github.com/ergochat/readline/blob/ced8f68a62a58e4be4e1b04cd1630a9f4ab9edd5/example/readline-pass-strength/readline-pass-strength.go#L83-L87

This is probably inherently race-y. We need more clarity about how the Listener API actually works.

**Comment by tpodowd** [comment]
This used to use the terminal.isReading variable (which was also racey) but for this particular issue it would work as the listener is called after it gets the enter key from the terminal and since the terminal returned the enter key, it has stopped reading. In the case of isPrompting, that will be true until data has been received by the operator outchan AND the operation lock is taken. The listener is called operator ioloop sends to the outchan. This is ok I think as long as the key is not enter...

the calling code looks like:
```
listener := o.GetConfig().Listener
if listener != nil {
    newLine, newPos, ok := listener.OnChange(o.buf.Runes(), o.buf.Pos(), r)
    if ok {
        o.buf.SetWithIdx(newPos, newLine)
    }
}
```

The Listeners (OnChange) job is to accept replacement input and a index position into it. Perhaps it is wrong to call the Listener here after we have just emptied the buffer and sent the data back to the caller anyway? Maybe that is the key issue? 

The refresh in the listener does allow programs like these to work though where the prompt can be redrawn to indicate some kind of status. I think removing the final call on return would fix this issue.

**Comment by slingamn** [comment]
I thought about it and I agree that suppressing the final SetPrompt/Refresh call is the correct fix for this application code (i.e. I no longer think that the behavior is inherently race-y). However, I'm not sure whether to fix this in the library itself or in the application code.

One thing I'm keeping in mind here is that we currently have the opportunity to break the API. The current API is somewhat unsystematic. For example, there is an initial invocation of `OnChange` even without a valid rune as input:

https://github.com/ergochat/readline/blob/86cc3492b2aaf7a8d29df9c75faf1c2648462ca5/operation.go#L404-L407

but the final invocation corresponding to the keypress of Enter is with an empty buffer and doesn't provide the opportunity to modify the line (although maybe that's unnecessary, since the caller can just modify the return value of `(*Instance).Readline()`?

So I'm thinking about ways to change the current API:

https://github.com/ergochat/readline/blob/86cc3492b2aaf7a8d29df9c75faf1c2648462ca5/operation.go#L575

so that it could give the listener an opportunity to make a final edit to the line, also possibly adding an argument so that it knows that this is the final call (and allowing it to suppress the SetPrompt/Refresh call if necessary, as in the password demo example). Thoughts?

**Comment by slingamn** [comment]
@tpodowd : that reminds me, I think you said you are using listeners in your application? Could you say something about how you use them?

**Comment by tpodowd** [comment]
I have some prompts that only allow certain keys to be selected or combinations. like "0" or "1k" depending on other conditions. So if a user presses a wrong key, we silently remove it from what they entered... My other use case is to reset a timeout counter (but not actually modify anything).
