### ISSUE TITLE
After switch from chzyer, the test case failed

### ISSUE THREAD

**Issue by 81981266** [ergochat/readline#73]
After switch from chzyer, the test case failed.
First input a string, then sleep second, then input another string but not close the io. No readline result is shown. If I close the io, 2 inputs will return **at once**. But **for chzyer repo, it returns a result for each input separately**.

```golang
package main

import (
	"fmt"
	"github.com/ergochat/readline"
	"io"
	"strings"
	"time"
)

func main() {
	pr, pw := io.Pipe()
	go func() {
		pw.Write([]byte("ttian\x7f\x7fffeng\x7f\r"))
		time.Sleep(time.Second * 2)
		pw.Write([]byte("abcs\x7f\r"))
		//pw.Close()
	}()
	l, err := readline.NewEx(&readline.Config{
		Stdin:             pr,
		HistorySearchFold: true,
	})
	if err != nil {
		panic(err)
	}
	defer l.Close()
	l.CaptureExitSignal()
	//log.SetOutput(l.Stderr())
	for {
		line, err := l.Readline()

		if err == readline.ErrInterrupt {
			if len(line) == 0 {
				break
			} else {
				continue
			}
		} else if err == io.EOF {
			break
		}

		line = strings.TrimSpace(line)
		fmt.Println("note: line", line, "err: ", err)
	}
}
```

**Comment by slingamn** [comment]
This is actually related to d9af5677814aff2b7d23e63a3b43537baf37ed69 (although we were refactoring a lot back then so I wouldn't put too much stock in bisect results). The code is getting stuck here:

https://github.com/ergochat/readline/blob/01a3cc25c0bb62563f867b0e1dbc838c20fe37fd/operation.go#L419-L422

because the mock terminal created with `io.Pipe` is not capable of responding to cursor position requests.

You can hack around this by adding:

```go
    FuncIsTerminal: func() bool { return false },
```

to the `readline.Config` in your example. But I guess what I really want to know is: is there a regression in behavior for actual terminals that affects you? Or are you just trying to fix your automated tests?
